name: Bug Report
description: Create a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - timokoessler
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug you are experiencing and how to reproduce it.
      placeholder: What is the bug and what did you expect to happen? How can we reproduce the problem?
    validations:
      required: true
  - type: input
    id: error-message
    attributes:
      label: Provide the error message / stack trace
      placeholder: Paste the error message or stack trace here, if available
    validations:
      required: false
  - type: input
    id: win-version
    attributes:
      label: What version of Windows are you using?
      description: If possible, please enter not only Windows 10 / 11 but the entire version.
      placeholder: Your Windows version
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: What version of the app are you using?
      placeholder: The app version, e.g. 1.0.0
    validations:
      required: true
